// Lenny's Podcast Knowledge Base — Data Layer
const CATEGORIES = [
  {
    id: "pm",
    code: "PM",
    name: "Product Management Craft",
    icon: "🎯",
    color: "#d63031",
    gradient: "linear-gradient(135deg, #ff7675 0%, #fab1a0 100%)",
    description: "Master the art and science of product management — from frameworks and prioritization to design sprints and discovery.",
    folder: "01 - Product Management Craft",
    guests: [
      { name: "Adriel Frederick", topic: "Product management at scale", tags: ["LD"] },
      { name: "Annie Pearl", topic: "Product strategy, product-led growth at Calendly", tags: ["ST"] },
      { name: "Aparna Chennapragada", topic: "AI product development at Google", tags: ["AI"] },
      { name: "Ben Williams", topic: "Product management at scale, Snyk", tags: ["GR"] },
      { name: "Bob Baxley", topic: "Design leadership, product organization", tags: ["LD"] },
      { name: "Bob Moesta 2.0", topic: "Jobs-to-be-Done, customer research", tags: ["SU"] },
      { name: "Bob Moesta", topic: "Jobs-to-be-Done framework", tags: ["SU"] },
      { name: "Boris Cherny", topic: "Product engineering practices", tags: ["EN"] },
      { name: "Brandon Chu", topic: "Product management craft, principles", tags: ["LD"] },
      { name: "Camille Hearst", topic: "Product leadership", tags: ["LD"] },
      { name: "Christian Idiodi", topic: "Product management principles, empowered teams", tags: ["LD"] },
      { name: "Christina Wodtke", topic: "OKRs, goal-setting frameworks for product teams", tags: ["ST"] },
      { name: "Christine Itwaru", topic: "Product operations and scaling", tags: ["LD"] },
      { name: "Christopher Miller", topic: "Product strategy and execution", tags: ["ST"] },
      { name: "Claire Vo", topic: "AI-first product development", tags: ["AI"] },
      { name: "Donna Lichaw", topic: "Product storytelling and narrative design", tags: ["CO"] },
      { name: "Eeke de Milliano", topic: "Product craft and user research", tags: ["GR"] },
      { name: "Geoff Charles", topic: "Building products at scale", tags: ["GR"] },
      { name: "Hari Srinivasan", topic: "Product development and innovation", tags: ["ST"] },
      { name: "Hilary Gridley", topic: "Product leadership and execution", tags: ["LD"] },
      { name: "Ian McAllister", topic: "Product leadership at Amazon", tags: ["LD"] },
      { name: "Inbal S.", topic: "Product management insights", tags: ["LD"] },
      { name: "Itamar Gilad", topic: "Product strategy, RICE framework", tags: ["ST"] },
      { name: "Jackie Bavaro", topic: "PM career paths, interview prep", tags: ["CA"] },
      { name: "Jackson Shuttleworth", topic: "Product craft and decision-making", tags: ["ST"] },
      { name: "Jag Duggal", topic: "Product development and measurement", tags: ["GR"] },
      { name: "Jake Knapp + John Zeratsky 2.0", topic: "Design sprints and rapid product development", tags: ["ST"] },
      { name: "Jake Knapp + John Zeratsky", topic: "Design sprints methodology", tags: ["ST"] },
      { name: "Janna Bastow", topic: "Roadmapping and product planning", tags: ["ST"] },
      { name: "Jason Shah", topic: "AI product management", tags: ["AI"] },
      { name: "Jeanne Grosser", topic: "Product leadership and growth", tags: ["GR"] },
      { name: "Jeff Weinstein", topic: "Product craft at Stripe", tags: ["SU"] },
      { name: "Jeremy Henrickson", topic: "Product management and go-to-market", tags: ["MA"] },
      { name: "Jiaona Zhang", topic: "Leading product teams, Linktree", tags: ["LD"] },
      { name: "John Cutler", topic: "Product development process, team dynamics", tags: ["EN"] },
      { name: "John Mark Nickels", topic: "Product craft and strategy", tags: ["ST"] },
      { name: "Jules Walter", topic: "Product design and user experience", tags: ["LD"] },
      { name: "Julie Zhuo 2.0", topic: "Design leadership and product management", tags: ["LD"] },
      { name: "Julie Zhuo", topic: "Design leadership, management at Facebook", tags: ["LD"] },
      { name: "Karri Saarinen", topic: "Linear product craft, speed + quality", tags: ["EN"] },
      { name: "Katie Dill", topic: "Design excellence at Stripe", tags: ["LD"] },
      { name: "Keith Yandell", topic: "Product craft and iteration", tags: ["ST"] },
      { name: "Ken Norton", topic: "PM career, Google PM principles", tags: ["LD"] },
      { name: "Kenneth Berger", topic: "Product management at scale", tags: ["LD"] },
      { name: "Kevin Yien", topic: "Product development and execution", tags: ["GR"] },
      { name: "Kristen Berman", topic: "Behavioral science in product", tags: ["GR"] },
      { name: "Lane Shackleton", topic: "Product leadership at Coda", tags: ["GR"] },
      { name: "Maggie Crowley", topic: "PM craft, product strategy writing", tags: ["LD"] },
      { name: "Manik Gupta", topic: "Consumer product leadership, CPO role", tags: ["LD"] },
      { name: "Marty Cagan 2.0", topic: "Product org transformation, empowered teams", tags: ["LD"] },
      { name: "Marty Cagan", topic: "Product management principles, Inspired", tags: ["ST"] },
      { name: "Matt LeMay", topic: "PM value, avoiding low-impact work", tags: ["LD"] },
      { name: "Maya Prohovnik", topic: "Podcasting product, Spotify/Anchor", tags: ["GR"] },
      { name: "Mayur Kamat", topic: "PM career development, hiring PMs", tags: ["CA"] },
      { name: "Megan Cook", topic: "Product leadership at Atlassian/Jira", tags: ["LD"] },
      { name: "Melissa Perri + Denise Tilles", topic: "Product operations at scale", tags: ["LD"] },
      { name: "Melissa Perri", topic: "Agile critiques, product owner vs PM", tags: ["EN"] },
      { name: "Melissa", topic: "Product org problems, strategy, vision", tags: ["ST"] },
      { name: "Mihika Kapoor", topic: "Vision-setting, product craft at Figma", tags: ["LD"] },
      { name: "Nabeel S. Qureshi", topic: "Palantir PM approach, forward-deployed eng", tags: ["LD"] },
      { name: "Nan Yu", topic: "Speed + quality at Linear", tags: ["EN"] },
      { name: "Nickey Skarstad", topic: "Vision, goals, execution alignment", tags: ["LD"] },
      { name: "Nikita Miller", topic: "Product process, shipping velocity", tags: ["LD"] },
      { name: "Noah Weiss", topic: "PM traits, product leadership at Slack", tags: ["LD"] },
      { name: "Paige Costello", topic: "Trust-building, PM coaching at Asana", tags: ["LD"] },
      { name: "Peter Deng", topic: "Product leadership at Facebook, Uber, OpenAI", tags: ["LD"] },
      { name: "Petra Wille", topic: "PM coaching, leadership development", tags: ["LD"] },
      { name: "Ravi Mehta", topic: "Product strategy, leadership frameworks", tags: ["ST"] },
      { name: "Ryan Singer", topic: "Shape Up methodology, Basecamp", tags: ["EN"] },
      { name: "Sanchan Saxena", topic: "Product dev process, working with CEOs", tags: ["LD"] },
      { name: "Scott Belsky", topic: "Product sense, consumer products, AI future", tags: ["AI"] },
      { name: "Shaun Clowes", topic: "PM discipline critique, AI for PMs", tags: ["AI"] },
      { name: "Shreyas Doshi Live", topic: "PM career questions, taste, listening", tags: ["CA"] },
      { name: "Shreyas Doshi", topic: "Pre-mortems, time management, prioritization", tags: ["ST"] },
      { name: "Shweta Shriva", topic: "PM at Waymo, self-driving product", tags: ["EN"] },
      { name: "Sriram and Aarthi", topic: "Consumer products, JTBD critique, content", tags: ["GR"] },
      { name: "Teresa Torres", topic: "Continuous discovery, opportunity solution tree", tags: ["GR"] },
      { name: "Upasna Gautam", topic: "Product at CNN, mindfulness for PMs", tags: ["CO"] },
      { name: "Varun Parmar", topic: "Miro product culture, competitive strategy", tags: ["ST"] },
      { name: "Vijay", topic: "Mixpanel product journey, focus vs expand", tags: ["ST"] },
      { name: "Vikrama Dhiman", topic: "PM career growth in Asia", tags: ["CA"] },
      { name: "Yuhki Yamashata", topic: "Figma CPO, product design craft", tags: ["SU"] }
    ]
  },
  {
    id: "growth",
    code: "GR",
    name: "Growth & Acquisition",
    icon: "📈",
    color: "#00b894",
    gradient: "linear-gradient(135deg, #55efc4 0%, #81ecec 100%)",
    description: "Unlock user growth through experimentation, loops, SEO, virality, and data-driven acquisition strategies.",
    folder: "02 - Growth & Acquisition",
    guests: [
      { name: "Adam Fishman", topic: "Growth leadership, building growth teams", tags: ["PM"] },
      { name: "Adam Grenier", topic: "Growth marketing tactics and channels", tags: ["MA"] },
      { name: "Alex Hardimen", topic: "Growth at Meta/Facebook", tags: ["PM"] },
      { name: "Alexander Embiricos", topic: "Experimentation, A/B testing at scale", tags: ["PM"] },
      { name: "Andy Johns", topic: "Growth frameworks, early growth at Facebook/Twitter", tags: ["ST"] },
      { name: "Anuj Rathi", topic: "Growth and product at scale in India", tags: ["PM"] },
      { name: "Archie Abrams", topic: "Growth at LinkedIn, marketplace dynamics", tags: ["MK"] },
      { name: "Austin Hay", topic: "Growth engineering, marketing tech stack", tags: ["MA"] },
      { name: "Bangaly Kaba", topic: "Growth at Instagram, growth loops", tags: ["PM"] },
      { name: "Benjamin Lauzier", topic: "Growth at Spotify, experimentation", tags: ["PM"] },
      { name: "Brian Balfour", topic: "Growth frameworks, Reforge", tags: ["ST"] },
      { name: "Brian Tolkin", topic: "Growth at scale", tags: ["PM"] },
      { name: "Casey Winters", topic: "Growth strategy, product-led growth", tags: ["ST"] },
      { name: "Crystal W.", topic: "Data-driven growth at Gojek", tags: ["PM"] },
      { name: "Ebi Atawodi", topic: "Growth at Netflix, Uber", tags: ["MK"] },
      { name: "Elena Verna 2.0", topic: "PLG, growth strategy, B2B growth", tags: ["ST"] },
      { name: "Elena Verna 3.0", topic: "Product-led growth and enterprise motion", tags: ["ST"] },
      { name: "Elena Verna 4.0", topic: "Advanced PLG strategy and execution", tags: ["ST"] },
      { name: "Eli Schwartz", topic: "SEO strategy and organic growth", tags: ["MA"] },
      { name: "Ethan Smith", topic: "Growth at scale and monetization", tags: ["PM"] },
      { name: "Fareed Mosavat", topic: "Growth at Slack, experimentation", tags: ["PM"] },
      { name: "Gaurav Misra", topic: "Growth and product strategy", tags: ["PM"] },
      { name: "Gina Gotthilf", topic: "Growth at Duolingo, international growth", tags: ["MA"] },
      { name: "Grant Lee", topic: "Growth channels and optimization", tags: ["PM"] },
      { name: "Gustaf Alstromer", topic: "YC growth advice, early-stage growth", tags: ["SU"] },
      { name: "Hila Qu", topic: "Growth at GitLab", tags: ["PM"] },
      { name: "Jess Lachs", topic: "DoorDash growth strategy", tags: ["PM"] },
      { name: "Laura Schaffer", topic: "Growth and experimentation", tags: ["PM"] },
      { name: "Lauryn Isford", topic: "Growth at Notion", tags: ["PM"] },
      { name: "Luc Levesque", topic: "Growth at Shopify/Facebook, SEO", tags: ["LD"] },
      { name: "Melissa Tan", topic: "Growth team building, Dropbox B2B", tags: ["LD"] },
      { name: "Meltem Kuran", topic: "Growth at Deel, SEO, paid ads", tags: ["MA"] },
      { name: "Merci Grace", topic: "PLG at Slack, head of growth hiring", tags: ["PM"] },
      { name: "Nilan Peiris", topic: "Word-of-mouth growth at Wise", tags: ["PM"] },
      { name: "Noam Lovinsky", topic: "Growth at YouTube, Thumbtack, Facebook", tags: ["PM"] },
      { name: "Oji Udezue", topic: "PLG, virality, ICP at Typeform", tags: ["PM"] },
      { name: "Ronny Kohavi", topic: "A/B testing, experimentation at scale", tags: ["PM"] },
      { name: "Sachin Monga", topic: "Substack growth, recommendations", tags: ["PM"] },
      { name: "Sean Ellis", topic: "PMF survey, Sean Ellis test", tags: ["SU"] },
      { name: "Sri Batchu", topic: "B2B growth at Ramp, growth channels", tags: ["SA"] },
      { name: "Tomer Cohen", topic: "LinkedIn product turnaround, AI-first feed", tags: ["AI"] },
      { name: "Yuriy Timen", topic: "Growth channels, Grammarly growth", tags: ["MA"] }
    ]
  },
  {
    id: "strategy",
    code: "ST",
    name: "Product Strategy",
    icon: "🗺️",
    color: "#0984e3",
    gradient: "linear-gradient(135deg, #74b9ff 0%, #a29bfe 100%)",
    description: "Think strategically about competitive positioning, decision-making, and long-term product vision.",
    folder: "03 - Product Strategy",
    guests: [
      { name: "Albert Cheng", topic: "Streaming strategy, content business at Amazon", tags: ["LD"] },
      { name: "Annie Duke", topic: "Decision-making under uncertainty", tags: ["PM"] },
      { name: "Geoffrey Moore", topic: "Crossing the Chasm, technology adoption lifecycle", tags: ["MA"] },
      { name: "Gibson Biddle", topic: "Netflix strategy, DHM model", tags: ["PM"] },
      { name: "Hamilton Helmer", topic: "7 Powers framework, strategic power", tags: ["SU"] },
      { name: "Richard Rumelt", topic: "Strategy frameworks, Good Strategy Bad Strategy", tags: ["LD"] },
      { name: "Roger Martin", topic: "Strategy choice cascade, playing to win", tags: ["LD"] },
      { name: "Shishir Mehrotra", topic: "Growth loops, rituals, Eigenquestions", tags: ["GR"] }
    ]
  },
  {
    id: "leadership",
    code: "LD",
    name: "Leadership & Management",
    icon: "👔",
    color: "#e17055",
    gradient: "linear-gradient(135deg, #fab1a0 0%, #ffeaa7 100%)",
    description: "Lead with clarity and build high-performing teams — from executive coaching to scaling company culture.",
    folder: "04 - Leadership & Management",
    guests: [
      { name: "Alisa Cohn", topic: "Executive coaching, leadership development", tags: ["CA"] },
      { name: "Ami Vora", topic: "Product leadership at Meta/WhatsApp", tags: ["PM"] },
      { name: "Anneka Gupta", topic: "Product leadership at scale, LinkedIn", tags: ["PM"] },
      { name: "Asha Sharma", topic: "Leadership at Poshmark, operating culture", tags: ["PM"] },
      { name: "Ben Horowitz", topic: "CEO coaching, company building", tags: ["SU"] },
      { name: "Bill Carr", topic: "Amazon leadership principles, product dev", tags: ["ST"] },
      { name: "Boz", topic: "Engineering and product leadership at Meta", tags: ["PM"] },
      { name: "Bret Taylor", topic: "Tech leadership at Salesforce, AI future", tags: ["AI"] },
      { name: "Brian Chesky", topic: "Founder-led product, Airbnb turnaround", tags: ["SU"] },
      { name: "Chip Conley", topic: "Modern elder, wisdom in leadership", tags: ["CA"] },
      { name: "Claire Butler", topic: "People operations and leadership", tags: ["CA"] },
      { name: "Claire Hughes Johnson", topic: "Scaling operations, Stripe leadership", tags: ["PM"] },
      { name: "Deb Liu", topic: "Leadership, career advice, overcoming bias", tags: ["CA"] },
      { name: "Elizabeth Stone", topic: "Data-driven leadership at Netflix", tags: ["AI"] },
      { name: "Ethan Evans 2.0", topic: "VP-level career growth at Amazon", tags: ["CA"] },
      { name: "Gokul Rajaram", topic: "Decision-making frameworks, leadership", tags: ["PM"] },
      { name: "Heidi Helfand", topic: "Dynamic reteaming, team transitions", tags: ["PM"] },
      { name: "Jason Fried", topic: "Basecamp philosophy, calm company", tags: ["PM"] },
      { name: "Jeffrey Pfeffer", topic: "Power dynamics, organizational politics", tags: ["CA"] },
      { name: "Jerry Colonna", topic: "CEO coaching, radical self-inquiry", tags: ["CA"] },
      { name: "Jonathan Lowenhar", topic: "Executive leadership coaching", tags: ["CA"] },
      { name: "Judd Antin", topic: "Research leadership and team culture", tags: ["PM"] },
      { name: "Kim Scott", topic: "Radical Candor, feedback culture", tags: ["CA"] },
      { name: "Lauren Ipsen", topic: "Leadership transitions and growth", tags: ["CA"] },
      { name: "Matt MacInnis", topic: "High-performance culture at Rippling", tags: ["PM"] },
      { name: "Matt Mochary", topic: "Executive coaching, CEO skills", tags: ["CA"] },
      { name: "Molly Graham", topic: "Giving away Legos, scaling teams", tags: ["CA"] },
      { name: "Naomi Gleit", topic: "Meta product leadership, productivity", tags: ["PM"] },
      { name: "Rachel Lockett", topic: "Executive coaching, difficult conversations", tags: ["CA"] },
      { name: "Ray Cao", topic: "TikTok culture, product operations", tags: ["PM"] },
      { name: "Tamar Yehoshua", topic: "Cross-functional leadership, AI products", tags: ["AI"] }
    ]
  },
  {
    id: "ai",
    code: "AI",
    name: "AI & Technology",
    icon: "🤖",
    color: "#6c5ce7",
    gradient: "linear-gradient(135deg, #a29bfe 0%, #74b9ff 100%)",
    description: "Navigate the AI revolution — from building AI products and prompt engineering to the future of coding and technology.",
    folder: "05 - AI & Technology",
    guests: [
      { name: "Aishwarya Naresh Reganti + Kiriti Badam", topic: "AI/ML product development", tags: ["PM"] },
      { name: "Alex Komoroske", topic: "AI strategy, systems thinking", tags: ["ST"] },
      { name: "Anton Osika", topic: "AI coding tools, Lovable", tags: ["EN"] },
      { name: "Benjamin Mann", topic: "AI company building, Anthropic", tags: ["SU"] },
      { name: "Chip Huyen", topic: "ML engineering, AI infrastructure", tags: ["EN"] },
      { name: "Dan Shipper", topic: "AI workflows, building with LLMs", tags: ["PM"] },
      { name: "Daniel Lereya", topic: "AI product strategy and development", tags: ["PM"] },
      { name: "Dr. Fei Fei Li", topic: "Computer vision, AI research at Stanford", tags: ["EN"] },
      { name: "Edwin Chen", topic: "AI quality, data labeling at scale", tags: ["PM"] },
      { name: "Hamel Husain & Shreya Shankar", topic: "LLM evaluation and fine-tuning", tags: ["EN"] },
      { name: "Karina Nguyen", topic: "AI research, knowledge tools", tags: ["PM"] },
      { name: "Kevin Weil", topic: "AI product leadership at OpenAI", tags: ["PM"] },
      { name: "Lazar Jovanovic", topic: "AI-powered development tools", tags: ["EN"] },
      { name: "Logan Kilpatrick", topic: "Developer relations, AI community", tags: ["PM"] },
      { name: "Marc Andreessen", topic: "AI future, venture capital, tech trends", tags: ["SU"] },
      { name: "Marily Nika", topic: "AI for product managers", tags: ["PM"] },
      { name: "Michael Truell", topic: "Building Cursor, AI coding", tags: ["SU"] },
      { name: "Mike Krieger", topic: "AI at Anthropic, Claude, eng productivity", tags: ["EN"] },
      { name: "Nick Turley", topic: "ChatGPT product development at OpenAI", tags: ["PM"] },
      { name: "Paul Adams", topic: "AI product strategy at Intercom", tags: ["PM"] },
      { name: "Robby Stein", topic: "Google Search AI, product evolution", tags: ["PM"] },
      { name: "Ryan J. Salva", topic: "GitHub Copilot, incubating big bets", tags: ["PM"] },
      { name: "Sam Schillace", topic: "Innovation, Google Docs origin, career", tags: ["CA"] },
      { name: "Sander Schulhoff 2.0", topic: "AI security, guardrails, prompt injection", tags: ["EN"] },
      { name: "Sander Schulhoff", topic: "Prompt engineering techniques", tags: ["PM"] },
      { name: "Scott Wu", topic: "Devin AI, autonomous coding agents", tags: ["EN"] },
      { name: "Sherwin Wu", topic: "AI coding at OpenAI, future of engineering", tags: ["EN"] },
      { name: "Tomer Cohen 2.0", topic: "Full-stack builder model at LinkedIn", tags: ["LD"] },
      { name: "Varun Mohan", topic: "AI coding tools, Codeium/Windsurf", tags: ["SU"] },
      { name: "Zevi Arnovitz", topic: "Non-technical PM building with AI", tags: ["PM"] }
    ]
  },
  {
    id: "startups",
    code: "SU",
    name: "Startups & Founding",
    icon: "🚀",
    color: "#fdcb6e",
    gradient: "linear-gradient(135deg, #ffeaa7 0%, #fab1a0 100%)",
    description: "From zero to one — founding stories, product-market fit, fundraising, and the rollercoaster of startup life.",
    folder: "06 - Startups & Founding",
    guests: [
      { name: "Amjad Masad", topic: "Building Replit, AI-first dev tools", tags: ["AI"] },
      { name: "Andrew Wilkinson", topic: "Building a portfolio of businesses", tags: ["LD"] },
      { name: "Ayo Omojola", topic: "Fintech product building", tags: ["PM"] },
      { name: "Brendan Foody", topic: "Startup building, creative products", tags: ["PM"] },
      { name: "Brian Halligan", topic: "HubSpot founding, inbound marketing", tags: ["GR"] },
      { name: "Cam Adams", topic: "Canva founding and scaling, culture", tags: ["LD"] },
      { name: "Dalton Caldwell", topic: "Y Combinator, startup advice", tags: ["PM"] },
      { name: "Dharmesh Shah", topic: "HubSpot founding, culture code", tags: ["LD"] },
      { name: "Drew Houston", topic: "Dropbox founding and scaling", tags: ["LD"] },
      { name: "Dylan Field 2.0", topic: "Figma scaling, product design vision", tags: ["PM"] },
      { name: "Dylan Field", topic: "Figma founding, product design tools", tags: ["PM"] },
      { name: "Eoghan McCabe", topic: "Intercom founding and leadership", tags: ["LD"] },
      { name: "Eric Ries", topic: "Lean Startup methodology", tags: ["PM"] },
      { name: "Eric Simons", topic: "StackBlitz founding, developer tools", tags: ["EN"] },
      { name: "Garrett Lord", topic: "Handshake founding, career platform", tags: ["GR"] },
      { name: "Guillermo Rauch", topic: "Vercel founding, developer tools", tags: ["EN"] },
      { name: "Howie Liu", topic: "Airtable founding, no-code platforms", tags: ["PM"] },
      { name: "Ivan Zhao", topic: "Notion founding, knowledge tools", tags: ["PM"] },
      { name: "Jason Cohen", topic: "WP Engine founding, bootstrapping vs VC", tags: ["ST"] },
      { name: "Jason Droege", topic: "Startup building and scaling", tags: ["PM"] },
      { name: "Jen Abel 2.0", topic: "Go-to-market, early sales strategy", tags: ["SA"] },
      { name: "Jen Abel", topic: "First customer acquisition for startups", tags: ["SA"] },
      { name: "Jessica Livingston", topic: "Y Combinator co-founder, startup advice", tags: ["LD"] },
      { name: "Josh Miller", topic: "The Browser Company, Arc founding", tags: ["PM"] },
      { name: "Julia Schottenstein", topic: "Consumer startup building", tags: ["PM"] },
      { name: "Kayvon Beykpour", topic: "Twitter/Periscope founding, live video", tags: ["PM"] },
      { name: "Keith Coleman & Jay Baxter", topic: "Twitter product evolution", tags: ["PM"] },
      { name: "Kevin Aluwi", topic: "Gojek founding, super app scaling", tags: ["GR"] },
      { name: "Kunal Shah", topic: "CRED founding, Indian tech ecosystem", tags: ["GR"] },
      { name: "Laura Modi", topic: "Bobbie founding, DTC brand building", tags: ["PM"] },
      { name: "Marc Benioff", topic: "Salesforce founding, CEO leadership", tags: ["LD"] },
      { name: "Matt Mullenweg", topic: "WordPress/open source, founder challenges", tags: ["LD"] },
      { name: "Melanie Perkins", topic: "Canva founding, crazy big goals", tags: ["LD"] },
      { name: "Mike Maples Jr", topic: "Breakthrough startup ideas, inflections", tags: ["ST"] },
      { name: "Nikita Bier", topic: "Viral consumer apps, tbh", tags: ["GR"] },
      { name: "Raaz Herzberg", topic: "Early-stage pivots, finding PMF", tags: ["PM"] },
      { name: "Rahul Vohra", topic: "PMF measurement, Superhuman", tags: ["PM"] },
      { name: "Ryan Hoover", topic: "Product Hunt founding, startup anxiety", tags: ["PM"] },
      { name: "Stewart Butterfield", topic: "Slack founding, product quality craft", tags: ["PM"] },
      { name: "Tanguy Crusson", topic: "0→1 inside large companies, Atlassian", tags: ["PM"] },
      { name: "Tobi Lutke", topic: "Shopify vision, long-term thinking", tags: ["LD"] },
      { name: "Todd Jackson", topic: "Product-market fit framework, stages", tags: ["PM"] },
      { name: "Uri Levine 2.0", topic: "Startup crisis management, resilience", tags: ["LD"] },
      { name: "Uri Levine", topic: "Waze founding, falling in love with problems", tags: ["LD"] }
    ]
  },
  {
    id: "marketplaces",
    code: "MK",
    name: "Marketplaces & Platforms",
    icon: "🏪",
    color: "#00cec9",
    gradient: "linear-gradient(135deg, #81ecec 0%, #55efc4 100%)",
    description: "Build and scale two-sided marketplaces — network effects, engagement hierarchies, and platform strategy.",
    folder: "07 - Marketplaces & Platforms",
    guests: [
      { name: "Chandra Janakiraman", topic: "Marketplace products, eBay evolution", tags: ["PM"] },
      { name: "Dan Hockenmaier", topic: "Marketplace growth, Thumbtack", tags: ["GR"] },
      { name: "Ramesh Johari", topic: "Marketplace design, data science", tags: ["GR"] },
      { name: "Sarah Tavel", topic: "Hierarchy of engagement/marketplaces", tags: ["GR"] },
      { name: "Tim Holley", topic: "Etsy marketplace growth, culture change", tags: ["GR"] }
    ]
  },
  {
    id: "pricing",
    code: "PR",
    name: "Pricing & Monetization",
    icon: "💰",
    color: "#f39c12",
    gradient: "linear-gradient(135deg, #f9ca24 0%, #ffeaa7 100%)",
    description: "Unlock revenue through pricing strategy, willingness-to-pay research, and modern monetization models.",
    folder: "08 - Pricing & Monetization",
    guests: [
      { name: "Madhavan Ramanujam 2.0", topic: "AI pricing, monetization strategy", tags: ["AI"] },
      { name: "Madhavan Ramanujam", topic: "Pricing strategy, willingness to pay", tags: ["PM"] },
      { name: "Naomi Ionita", topic: "Monetization strategy, modern growth stack", tags: ["GR"] },
      { name: "Patrick Campbell", topic: "SaaS pricing, retention, ProfitWell", tags: ["GR"] }
    ]
  },
  {
    id: "communication",
    code: "CO",
    name: "Communication & Storytelling",
    icon: "🎤",
    color: "#e84393",
    gradient: "linear-gradient(135deg, #fd79a8 0%, #ff7675 100%)",
    description: "Communicate with impact — from public speaking and strategic narrative to storytelling frameworks.",
    folder: "09 - Communication & Storytelling",
    guests: [
      { name: "Andy Raskin", topic: "Strategic narrative, messaging", tags: ["MA"] },
      { name: "David Placek", topic: "Naming strategy, brand naming", tags: ["MA"] },
      { name: "Evan LaPointe", topic: "Communication strategy and frameworks", tags: ["LD"] },
      { name: "Jason Feifer", topic: "Storytelling in business contexts", tags: ["SU"] },
      { name: "Jessica Hische", topic: "Lettering, design, creative careers", tags: ["CA"] },
      { name: "Lulu Cheng Meservey", topic: "PR and communications strategy", tags: ["MA"] },
      { name: "Matt Abrahams", topic: "Public speaking, spontaneous communication", tags: ["CA"] },
      { name: "Matthew Dicks", topic: "Storytelling techniques, Storyworthy", tags: ["CA"] },
      { name: "Nancy Duarte", topic: "Presentations, persuasive communication", tags: ["LD"] },
      { name: "Tristan de Montebello", topic: "Public speaking skills, Ultraspeaking", tags: ["CA"] },
      { name: "Wes Kao 2.0", topic: "Communication frameworks, MOO, writing", tags: ["LD"] },
      { name: "Wes Kao", topic: "Managing up, writing better, Maven", tags: ["CA"] }
    ]
  },
  {
    id: "career",
    code: "CA",
    name: "Career & Personal Development",
    icon: "🧭",
    color: "#a29bfe",
    gradient: "linear-gradient(135deg, #dfe6e9 0%, #a29bfe 100%)",
    description: "Navigate your career path — from finding meaningful work and building networks to personal growth and focus.",
    folder: "10 - Career & Personal Development",
    guests: [
      { name: "Ada Chen Rekhi", topic: "Career optimization, finding meaningful work", tags: ["PM"] },
      { name: "Carole Robin", topic: "Interpersonal dynamics, leadership psychology", tags: ["LD"] },
      { name: "Chris Hutchins", topic: "Life optimization, personal finance", tags: ["PM"] },
      { name: "Dr. Becky Kennedy", topic: "Parenting, psychology, leadership parallels", tags: ["LD"] },
      { name: "EOY Review", topic: "End-of-year reflections and lessons", tags: ["PM"] },
      { name: "Failure", topic: "Lessons from failure, resilience", tags: ["SU"] },
      { name: "Graham Weaver", topic: "Living an intentional life, risk-taking", tags: ["SU"] },
      { name: "Joe Hudson", topic: "Emotional intelligence, self-awareness", tags: ["LD"] },
      { name: "Jonny Miller", topic: "Nervous system mastery, performance optimization", tags: ["PM"] },
      { name: "Nikhyl Singhal", topic: "PM career stages, avoiding traps", tags: ["PM"] },
      { name: "Nir Eyal", topic: "Focus, avoiding distraction, Indistractable", tags: ["PM"] },
      { name: "Paul Millerd", topic: "Alternative career paths, Pathless Path", tags: ["SU"] },
      { name: "Phyl Terry", topic: "Job searching, candidate-market fit", tags: ["PM"] },
      { name: "Sam Lessin", topic: "Professional etiquette, networking", tags: ["LD"] },
      { name: "Tom Conrad", topic: "Career choices, failure lessons, Pandora/Snap", tags: ["SU"] }
    ]
  },
  {
    id: "marketing",
    code: "MA",
    name: "Marketing & Branding",
    icon: "📣",
    color: "#ff6b6b",
    gradient: "linear-gradient(135deg, #ff9ff3 0%, #ff6b6b 100%)",
    description: "Build brands that resonate — from positioning and naming to content marketing and demand generation.",
    folder: "11 - Marketing & Branding",
    guests: [
      { name: "April Dunford 2.0", topic: "Product positioning, sales pitches", tags: ["ST"] },
      { name: "April Dunford", topic: "Product positioning methodology", tags: ["ST"] },
      { name: "Arielle Jackson", topic: "Naming, positioning, brand for startups", tags: ["SU"] },
      { name: "Barbra Gago", topic: "Demand gen, marketing strategies", tags: ["GR"] },
      { name: "Camille Ricketts", topic: "Content marketing, communications", tags: ["CO"] },
      { name: "Carilu Dietrich", topic: "CMO insights, IPO marketing", tags: ["SU"] },
      { name: "Christopher Lochhead", topic: "Category design, category creation", tags: ["ST"] },
      { name: "Emilie Gerber", topic: "PR and marketing for startups", tags: ["SU"] },
      { name: "Emily Kramer", topic: "Marketing org building, B2B marketing", tags: ["GR"] },
      { name: "Gia Laudi", topic: "Customer-led growth marketing", tags: ["GR"] },
      { name: "Julian Shapiro", topic: "Content strategy, growth marketing", tags: ["GR"] },
      { name: "Krithika Shankarraman", topic: "Growth marketing at Stripe", tags: ["GR"] },
      { name: "Seth Godin", topic: "Branding, strategy, tension in marketing", tags: ["ST"] },
      { name: "Timothy Davis", topic: "Performance marketing, paid ads", tags: ["GR"] },
      { name: "Zoelle Egner", topic: "Startup marketing, Airtable growth", tags: ["GR"] }
    ]
  },
  {
    id: "sales",
    code: "SA",
    name: "Sales",
    icon: "🤝",
    color: "#b2bec3",
    gradient: "linear-gradient(135deg, #dfe6e9 0%, #b2bec3 100%)",
    description: "Close deals and build revenue engines — from founding sales to enterprise SaaS methodology.",
    folder: "12 - Sales",
    guests: [
      { name: "Jason M Lemkin", topic: "SaaS sales, SaaStr community", tags: ["SU"] },
      { name: "Jonathan Becker", topic: "Enterprise sales strategy", tags: ["SU"] },
      { name: "Matt Dixon", topic: "Sales methodology, JOLT method", tags: ["GR"] },
      { name: "Pete Kazanjy", topic: "Founding sales, first sales hire", tags: ["SU"] },
      { name: "Sahil Mansuri", topic: "Sales during downturns, B2B sales", tags: ["SU"] }
    ]
  },
  {
    id: "engineering",
    code: "EN",
    name: "Engineering & DevEx",
    icon: "⚙️",
    color: "#2d3436",
    gradient: "linear-gradient(135deg, #636e72 0%, #b2bec3 100%)",
    description: "Build better engineering cultures — from developer productivity and platform teams to eng-PM dynamics.",
    folder: "13 - Engineering & DevEx",
    guests: [
      { name: "Camille Fournier", topic: "Engineering management, org design", tags: ["LD"] },
      { name: "David Singleton", topic: "Engineering at Stripe, AI tools", tags: ["AI"] },
      { name: "Dhanji R. Prasanna", topic: "Engineering culture, developer experience", tags: ["LD"] },
      { name: "Dmitry Zlokazov", topic: "Developer tooling and productivity", tags: ["PM"] },
      { name: "Farhan Thawar", topic: "Engineering leadership, shipping fast", tags: ["LD"] },
      { name: "Gergely", topic: "Engineering career, industry insights", tags: ["CA"] },
      { name: "Gustav Söderström", topic: "Spotify engineering culture, innovation", tags: ["LD"] },
      { name: "Nicole Forsgren 2.0", topic: "Productivity metrics, AI impact on eng", tags: ["AI"] },
      { name: "Nicole Forsgren", topic: "DORA, SPACE, developer productivity", tags: ["LD"] },
      { name: "Will Larson", topic: "Eng strategy, eng-PM relationship", tags: ["LD"] }
    ]
  }
];

// Tag display names
const TAG_NAMES = {
  PM: "Product", GR: "Growth", ST: "Strategy", LD: "Leadership",
  AI: "AI/Tech", SU: "Startups", MK: "Marketplace", PR: "Pricing",
  CO: "Comms", CA: "Career", MA: "Marketing", SA: "Sales", EN: "Engineering"
};

// Tag colors
const TAG_COLORS = {
  PM: "#d63031", GR: "#00b894", ST: "#0984e3", LD: "#e17055",
  AI: "#6c5ce7", SU: "#fdcb6e", MK: "#00cec9", PR: "#f39c12",
  CO: "#e84393", CA: "#a29bfe", MA: "#ff6b6b", SA: "#b2bec3", EN: "#2d3436"
};
